### ISSUE TITLE
Add ButterFaces autoconfiguration

### ISSUE THREAD

**Issue by persapiens** [persapiens/jsf-spring-boot-starter#122]

**Comment by larmic** [comment]
That would be very nice!

**Comment by persapiens** [comment]
I'll be a pleasure @larmic .

I've read a bit about ButterFaces and I think we'll work with it this month.

Could you:

- give some advice about ButterFaces compatibility with current supported jsf libraries by Jsf Spring Boot Starter (PrimeFaces, PrimeFaces Extensions, BootsFaces, AngularFaces, OmniFaces, Mojarra, MyFaces, Tomcat, Jetty and Undertow)?

- point some documentation about specific ButterFaces context-param?

- explain any important configuration tip to be known?

Sincerely,
Marcelo

**Comment by larmic** [comment]
Hi @persapiens 

ButterFaces is compatible with Mojarra, MyFaces, Tomcat, Jetty, Undertow and OmniFaces.

* When using PrimeFaces there is something todo (https://butterfaces.gitbooks.io/butterfaces/content/primefaces_integration.html) but we are working on an automatic way.
* When using BootsFaces context param net.bootsfaces.get_jquery_from_cdn must be set to true.
* We have not tried using ButterFaces and AngularFaces so far.

All context param configuration can be found here: https://butterfaces.gitbooks.io/butterfaces/content/configuration.html

Normally there is nothing special to do. Just add ButterFaces dependency and it works out-of-the-box. Using PrimeFaces or BootsFaces in combination with ButterFaces is a bit tricky.

Yours

Lars

**Comment by larmic** [comment]
Hi @persapiens 

ButterFaces 2.1.8 is released. With this version PrimeFaces integration works out-of-the-box.

**Comment by persapiens** [comment]
Thanks for your explanation.

Let's speed up ButterFaces autoconfiguration.

**Comment by persapiens** [comment]
Hi @larmic 

Some progress:
- created [butterfaces](https://github.com/persapiens/jsf-spring-boot-starter/tree/butterfaces) branch with initial implementation of ButterFaces autoconfiguration.
- forked [primefaces-integration](https://github.com/persapiens/primefaces-integration) example to use new jsf-butterfaces-spring-boot-starter with **success**.
- forked [bootsfaces-integration](https://github.com/persapiens/bootsfaces-integration) example to use new jsf-myfaces-butterfaces-spring-boot-starter with **success**.

Some notes:
1- Could not fork [omnifaces-integration](https://github.com/ButterFaces/omnifaces-integration) because the jsf spring boot starter use omnifaces 1.14. This version does not contain cdi stuff and does not require cdi runtime. However, I could test omnifaces with primefaces-integration example with **success**.
2- [jsf-bootsfaces-spring-boot-autoconfigure](https://github.com/persapiens/jsf-spring-boot-starter/blob/butterfaces/jsf-butterfaces-spring-boot-autoconfigure/src/main/java/com/github/persapiens/jsfboot/butterfaces/ButterfacesServletContextConfigurer.java) set **net.bootsfaces.get_jquery_from_cdn** to true in order to [ButterFaces and BootsFaces work together](https://github.com/ButterFaces/bootsfaces-integration/blob/master/README.md).
3- Ideally, we should use only six starters, because the user has to choose one servlet container (three options: Tomcat, Jetty and Undertow) and one jsf implementation (two options: Mojarra and MyFaces). And all jsf libraries should wok together.
4- However, we usually create more six specific starters for each jsf component library in order to work better with it, taking care of compatibility with others jsf libraries.

Some questions:
1- I didn't see any issues with OmniFaces, PrimeFaces and BootsFaces with ButterFaces. Do you see any to avoid them at ButterFaces starters? 
2- ButterFaces use all of web-xml parameters at [WebXmlParameters](https://github.com/ButterFaces/ButterFaces/blob/master/components/src/main/java/de/larmic/butterfaces/resolver/WebXmlParameters.java) ? In the meanwhile, [ButterfacesProperties](https://github.com/persapiens/jsf-spring-boot-starter/blob/butterfaces/jsf-butterfaces-spring-boot-autoconfigure/src/main/java/com/github/persapiens/jsfboot/butterfaces/ButterfacesProperties.java) is configuring all of them. 

I look forward your answer.

**Comment by larmic** [comment]
Hi @persapiens 

sorry for waiting but I'm on vacation. ;)

1 - I'm also didn't see any issues.
2 - Jetzt WebXmlParameter uses all web.xml parameters of ButterFaces

**Comment by persapiens** [comment]
Let's start release process as soon as possible.

Enjoy your vacation ;)
