### ISSUE TITLE
Jetty and Undertow support?

### ISSUE THREAD

**Issue by cemo** [persapiens/jsf-spring-boot-starter#28]
Hey, 

We are considering to move your project but seems a notice in homepage about tomcat. Is this library working only Tomcat? Ideally a Spring Boot starter would be run with Jetty and Undertow as well.

Thanks for sharing.

**Comment by persapiens** [comment]
Hi @cemo 

This library works with Jetty. However, some tricks should be done:
- add some jetty libraries (spring-boot-starter-jetty, javax.el, jetty-jsp, javax.servlet.jsp)
- remove some tomcat libraries (spring-boot-starter-tomcat, tomcat-embed-jasper, tomcat-embed-el)
- configure jsf to scan resources properly from classpath according to [@ghillert Demo Application](https://github.com/ghillert/spring-boot-jsp-demo/blob/jetty/src/main/java/com/hillert/JspDemoApplication.java). 

I think to create new **jsf-jetty-spring-boot-starter** to autoconfigure jetty. What do you think?

**Comment by persapiens** [comment]
This library works with Undertow also. However, some tricks should be done:
* add some undertow libraries (spring-boot-starter-undertow, javax.el, jboss-jsp-api_2.3_spec)
* remove some tomcat libraries (spring-boot-starter-tomcat, tomcat-embed-jasper, tomcat-embed-el)
* configure jsf to scan resources properly from classpath

I think to create new **jsf-undertow-spring-boot-starter** to autoconfigure undertow. What do you think?

**Comment by cemo** [comment]
+1 for starters. I am closing this one in favor of new ones.

**Comment by persapiens** [comment]
Hi @nyilmaz and @cemo .

I've just pushed first implementation to [**jsf**-jetty-spring-boot-starter](../issues/#33) and [**undertow**-jetty-spring-boot-starter](../issues/#36).
Both starters customize how to load jsf resources from classpath. Default folder is **META-INF/resources** (same as tomcat), but could be changed with application.properties.

If you want to test before release, do these steps:
* build jsf-spring-boot-starter project;
* change jsf-spring-boot-starter version to 1.2.0-SNAPSHOT at pom.xml of jsf-spring-boot-starter-example;
* if you would like to test **Jetty**, change artifactId of jsf-spring-boot-starter to jsf-jetty-spring-boot-starter to enable Jetty servlet container
* if you would like to test **Undertow**, change artifactId of jsf-spring-boot-starter to jsf-undertow-spring-boot-starter to enable Undertow servlet container

I wan to to release next friday 27/05.
