### ISSUE TITLE
Spring Security support

### ISSUE THREAD

**Issue by cemo** [persapiens/jsf-spring-boot-starter#29]
Would you consider to add support Spring Security as well? What I have done before is stripping necessary components from spring-webflow and put inside our project. Using directly spring-webflow is bringing other dependencies that is why we are not using directly using them.

Here is the relevant part of it:

https://github.com/spring-projects/spring-webflow/tree/ae25f24443a1756b1149a95200bbe9f04a24f911/spring-faces/src/main/java/org/springframework/faces/security

**Comment by persapiens** [comment]
@cemo , I think [jsf facelets spring security library](http://www.dominikdorn.com/facelets/) is exactly what you're looking for.
However, it was deployed at google code and it does not work anymore :(
I will contact dominik (library author) to know if he could deploy to maven central.

**Comment by persapiens** [comment]
@cemo what do you think about fork specific spring security facelets spring-webflow classes into these project? Create a separate project could be better approach?

**Comment by cemo** [comment]
Spring Team expects a contribution from community to support JSF. Almost all issues related to JSF has been marked as `contributions welcome` in JIRA. 

I think that this project would be the correct place to gather community efforts. 

So +1 to bring these classes into this project.

**Comment by persapiens** [comment]
Thank you for you comments @cemo. Let's do our best to improve JSF and Spring Boot ecosystem!

@domdorn answered me. His [spring security facelets taglib](https://github.com/domdorn/spring-security-facelets-taglib) is at github. He'll push maven central soon.

I'm a happy spring taglib-jsf20-spring-3 library user with jsf 2.2, spring 4.2 and springsecurity 4.2 versions.

The main advantage of [spring security facelets taglib](https://github.com/domdorn/spring-security-facelets-taglib) library over [spring-webflow](http://docs.spring.io/spring-webflow/docs/current/reference/html/spring-faces.html#spring-faces-security-taglib) is that it is dedicated to solve jsf facelets and spring security integration. The facelets tags are equivalent. Maybe including all spring-webflow stuff is not a good solution at this moment.

**Comment by persapiens** [comment]
@cemo , I've just pushed initial implementation of Spring Security Facelets Taglib support at JSF Spring Boot Starter integration submodule. ([branch security](https://github.com/persapiens/jsf-spring-boot-starter/tree/security))

It is a mixed solution from [spring webflow](http://docs.spring.io/spring-webflow/docs/current/reference/html/spring-faces.html#spring-faces-security-taglib) and from [@domdorn]( https://github.com/domdorn/spring-security-facelets-taglib).
 
Added springsecuritytaglib.xml including authorize, authenticated and anonymous tags and areAllGranted, areAnyGranted, areNotGranted, isAllowed, isAuthenticated and isAnonymous functions. 

JSF Spring Boot Starter included org.springframework.boot:spring-security-taglibs dependency. Client application has to include org.springframework.boot:spring-boot-starter-security dependency.

**Comment by nyilmaz** [comment]
Great!! I'll give a try asap.

**Comment by persapiens** [comment]
I've just pushed some changes related to reorganize classnames and introduced FullyAuthorized tag.

I look forward your accurate comments @nyilmaz

**Comment by nyilmaz** [comment]
I have successfully applied your snapshot version in which you did add taglibs. No problems so far. I also added a sample (in fact rearranged your example project). You can check it out @ https://github.com/nyilmaz/jsf-spring-boot-starter-example/commit/6195ad2052facedb56f25eac1146ae07f3974650

**Comment by persapiens** [comment]
Thanks a lot. I'll release it today. I'll rearrange example project with your code too.

**Comment by persapiens** [comment]
Implemented in #53
