### ISSUE TITLE
Remove RequestContextListener definition from MojarraSpringBootAutoConfiguration

### ISSUE THREAD

**Issue by nyilmaz** [persapiens/jsf-spring-boot-starter#30]
`RequestContextListener` bean definition blocks `WebMvcAutoConfiguration `s `RequestContextFilter` bean to be defined. 

https://github.com/spring-projects/spring-boot/blob/v1.3.5.RELEASE/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration.java#L184

Hence `ServletRequestAttributes` is not set appropriately (ie. `HttpServletResponse` is not set). 

The very same configuration is present for `MyFaces` also.

**Comment by persapiens** [comment]
Hi @nyilmaz 

I see your question, however `RequestContextListener` is usually commented as necessary when running [jsf + spring](http://stackoverflow.com/questions/5124622/jsf-2-and-spring-3-integration). 

Is it not necessary when integration Jsf + Spring Boot anymore?

**Comment by nyilmaz** [comment]
Well it seems this is the outdated version of setting things into work. See https://github.com/spring-projects/spring-boot/issues/2637. Besides, now, I am able to run your sample project with this issue applied and it worked flawlessly :).

The point here with `RequestContextFilter ` and `RequestContextListener ` is that both are setting `HttpServletRequest`. I _do not_ think things will get weird, when we remove `RequestContextListener`. Because in a typical webapp spring-boot will have already registered `RequestContextFilter` which is ordered early. Although if things get weird and does not work, you can provide both of above. This means an addition of `RequestContextFilter`. Thus `HttpServletResponse` will be set also.

Btw i did some refactoring into my jsf code replacing yours (using jetty server), I got it work too, without any modification (apart from some yaml configuration), fyi.

**Comment by persapiens** [comment]
Thanks for you explanation @nyilmaz . I'll be done at next release.

I'll create [jsf jetty spring boot starter](#33) also. I was suggested by @cemo in #28 .

Any help would be appreciated.
