### ISSUE TITLE
ClassCastException when HandlerWrappers are added via spring-boot for jetty starter

### ISSUE THREAD

**Issue by nyilmaz** [persapiens/jsf-spring-boot-starter#38]
Referring to https://github.com/spring-projects/spring-boot/blob/50e0bb2d9ca3d4d649ec55d135381102c6b6737d/spring-boot/src/main/java/org/springframework/boot/context/embedded/jetty/JettyEmbeddedServletContainerFactory.java#L166

If either of server header or gzip compression is enabled, `HandlerWrapper`s are added and [this](https://github.com/persapiens/jsf-spring-boot-starter/blob/master/jsf-jetty-spring-boot-autoconfigure/src/main/java/com/github/persapiens/jsfboot/jetty/JettySpringBootAutoConfiguration.java#L53) line breaks throwing `ClassCastException`. `Server.getHandler()` does not return `WebAppContext` anymore.

My first reaction was adding `@Order` to `JettySpringBootAutoConfiguration` but it did not work. Solution would be like;
```
          Handler[] childHandlersByClass = server.getChildHandlersByClass(WebAppContext.class);
           WebAppContext webAppContext = (WebAppContext) childHandlersByClass[0];
```

Keep up good work btw! Thanks!

**Comment by nyilmaz** [comment]
Updated sol'n...

**Comment by persapiens** [comment]
I've just pushed your code.

Thanks @nyilmaz
